### ISSUE TITLE
Governance of code lists

### ISSUE THREAD

**Issue by vcetl** [INSPIRE-MIF/helpdesk-registry#12]
Dear all,

It is clearly important to rightly distinguish governance of code lists. 

In the case of EU legal act (e.g. INSPIRE M&R decision) it is clear that it should be EU legal. In the case of recently added IACS code list, seems right to be under EU technical. It could be in future more cases like this which are not strictly falling under INSPIRE technical guidelines.

Should we also consider in that case to introduce another governance level (EU-good-practice or similar) to distinguish between technical (TGs) and good practices (GPs)? The item should be then governed at the level of an INSPIRE Good Practice.

Thank you & BR

Vlado

**Comment by hernlor** [comment]
Dear @vcetl  ,

thank you for your request, your proposal is now under scrutiny of the Control Body.

We understand that your proposal is: 

1) be to add another value for the "Governance level" code list/ column[1] so that it contains a "good practice" value as follows:

Label: Good  practice (EU) 
URI: https://inspire.ec.europa.eu/registry/governance-level/eu-good-practice
Definition: The item is governed at the level of an INSPIRE Good Practice.

2) Change the value of governance to the IACS code list recently added.

Kind regards,

INSPIRE Registry team.

[1] https://inspire.ec.europa.eu/registry/governance-level

**Comment by hernlor** [comment]
Dear @vcetl 

the new governance value is available at: https://inspire.ec.europa.eu/registry/governance-level/eu-good-practice
The [IACS code list](https://inspire.ec.europa.eu/metadata-codelist/IACSData) has been updated accordingly. 

Kind regards, 
INSPIRE registry team
