### ISSUE TITLE
Additional Survey Type

### ISSUE THREAD

**Issue by lvdbrink** [INSPIRE-MIF/helpdesk-registry#13]
URI http://inspire.ec.europa.eu/codelist/SurveyTypeValue

Motivation: 
- The list lacks the survey type of Vertical Geo Electric Measurement Cable
- The list lacks the survey type of Vertical Electromagnetic borehole sounding

Proposed change: Add to the list of survey types the values: 
- `Vertical Geo Electric Measurement Cable`
- `Vertical Electromagnetic borehole sounding`

Change type: Addition

**Comment by hernlor** [comment]
Dear @lvdbrink , 

thank you for your request.

Could you kindly let us know where the missing values come from please?

Kind regards, 

The INSPIRE registry team

**Comment by lvdbrink** [comment]
The missing values were suggested to me by the information modeling team working on the [Dutch National Key Registry of the Subsurface](https://basisregistratieondergrond.nl/english). 

They explained to me that they need these values in the context of groundwater monitoring, more specifically formation resistance surveys.

**Comment by hernlor** [comment]
Dear @lvdbrink , 

thank you for the information.

Since these values are not originally part of the INSPIRE data model for geology we cannot add them in the INSPIRE registry. 

However, as the code list "Survey Type"[1] is "_Extensible with values at any level_" you can make use of your own values in your datasets.

If you would like to share your extension of the code list with the rest of the INSPIRE community you can make use of the **register federation tool** .You can see some examples in [2].

[1] https://inspire.ec.europa.eu/codelist/SurveyTypeValue
[2] https://inspire-regadmin.jrc.ec.europa.eu/ror/

Kind regards, 
INSPIRE registry team
