### ISSUE TITLE
fix a reference to fao document

### ISSUE THREAD

**Issue by pvgenuchten** [INSPIRE-MIF/helpdesk-registry#22]
at https://inspire.ec.europa.eu/document/FaoMaster a reference is made to a non existing FAO document at ftp://ftp.fao.org/agl/agll/docs/guidel_soil_descr.pdf 

this document has moved to 
https://www.fao.org/3/a0541e/a0541e.pdf

this document location is referenced from various codelists, such as https://inspire.ec.europa.eu/codelist/FAOHorizonMasterValue

**Comment by arantzaetxebarria** [comment]
Dear @pvgenuchten 

This issue is duplicated and will be processed in [issue 33](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/33), where you will still be informed of the progress.
Therefore, this issue will be closed. 
If you have any questions, please do not hesitate to contact us.

Regards
