### ISSUE TITLE
Official reference systems of the Canary Islands

### ISSUE THREAD

**Issue by abadppa0** [INSPIRE-MIF/helpdesk-registry#25]
**Problem:** The GML files of the Canary Islands do not pass the validation requirements due to the fact that the official reference systems of the Canary Islands are not included among the CSRs listed on list of valid coordinate reference system identifiers.

**Description**:The official coordinate reference systems (CRS) of the Canary Islands are not approved. The CRS URIs of Canary are not listed in TG requirement 2.
The official CRS of the Canary Islands are:
http://www.opengis.net/def/crs/EPSG/0/4080
http://www.opengis.net/def/crs/EPSG/0/4081
http://www.opengis.net/def/crs/EPSG/0/4082
http://www.opengis.net/def/crs/EPSG/0/4083

According to the [documentation](https://github.com/inspire-eu-validation/data/blob/master/reference-systems/spatial.md) it says: _Additional values will be added to the list for regions outside of continental Europe, if nominated by a Member State and available in a CRS register with a persistent http URI_.

**Proposal:** Add on the "validation tool" and in the "INSPIRE Data Specifications" the official Canary Islands Coordinate Reference System Identifiers: 4080, 4081, 4082 and 4083.
Please let us know if this GitHub entry is sufficient to add CRSs or if a official notification from the Spanish contact point is required.

Thank you.

**Comment by heidivanparys** [comment]
This issue should be moved to https://github.com/INSPIRE-MIF/helpdesk/issues, and is related to the [issues labelled “CRS registry” in that helpdesk](https://github.com/INSPIRE-MIF/helpdesk/issues?q=is%3Aissue+is%3Aopen+label%3A%22CRS+registry%22).

In short, the following is needed:

1. Amendment to [IR 1089/2010](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN) to allow for a CRS registry to be established (the procedure for this amendment is ongoing: it has been in [public consultation](https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/13182-Sharing-geospatial-data-on-the-environment-INSPIRE-updated-rules-on-interoperability-of-spatial-data-sets-&-services_en), and now the [INSPIRE Committee](https://ec.europa.eu/transparency/comitology-register/screen/committees/C33600/consult) members have until the 10th of December to express their opinion). The changes relevant for this issue are the changes to section 1.3.4 in Annex II.
2. Creation of a CRS registry, including governance structure with a control body.
3. Update of the validator to validate against the CRS registry instead of against the current static list.
4. Approval of the control body to add EPSG:4080, EPSG:4081, EPSG:4082 and EPSG:4083 to the CRS registry (i.e., confirmation of the control body that these CRSs fulfil the requirements in the amended implementing rules.

**Comment by abadppa0** [comment]
Thank you. I close this issue and open on https://github.com/INSPIRE-MIF/helpdesk/issues
