### ISSUE TITLE
Priority Data Sets codelist not accessible: "There is a problem in the application"

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-registry#27]
**Problem:**
Priority Data Set codelist values are sometimes not displayed in INSPIRE Registry. Following error message was shown around 10.30h (UTC+1). 
![image](https://user-images.githubusercontent.com/38787131/149910110-8537dd5c-c3dc-45a7-8030-798eb3e1a6dc.png)

Codelist values are sometimes shown "immediatly" after the request has been sent and sometimes after few seconds.

Could you please tell why this happens?

**Steps to reproduce**
1. Try to access https://inspire.ec.europa.eu/metadata-codelist/PriorityDataset several times

**Comment by oscar9** [comment]
Dear,

This is probably a software related problem. We have in mind and already some ideas in development to improve the performance and a better ways to handle the cache of the application in order to be quicker when it loads. 
We will transfer this issue to the re3gistry software repository in order to check this example in the future and keep you informed. 

https://github.com/ec-jrc/re3gistry/issues/161

Thanks for your comment

**Comment by oscar9** [comment]
Dear,

We will let this issue open until it's fixed and checked in INSPIRE Registry.

Thanks

**Comment by arantzaetxebarria** [comment]
Dear user,

It seems that right now the access to https://inspire.ec.europa.eu/metadata-codelist/PriorityDataset works properly.
If you experience any further problems, please do not hesitate to open a new issue.

Regards,

Arantza
