### ISSUE TITLE
Missing register in landing page of registry

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-registry#29]
Dear Re3gistry Team,

any idea, why we are not able to see this testing Register https://er.hany.sk/extensions 
also on the landing page of the Re3gistry? https://er.hany.sk/registry

Thanks in advance, 

best regards, Martin

**Comment by emanuelaepure10** [comment]
Hi @MartinTuchyna & @MichalMed ,

Can I ask you how you have create the register?
From the management interface?

Do you see it in the management interface as a part of the registry?

if so, probably you need to remove the cache folder from you file system and try to reload the page.

Soon we have released a new version of the software which is updating the cache once 'something' has been change on the management interface.

Please let us know if removing the cache or after a update the problem has need solved

Thank you in advanced

**Comment by arantzaetxebarria** [comment]
Dear @MartinTuchyna and @MichalMed 

After the analysis, it has been decided that this issue is related to the Re3gistry software and the better place to be solved in the most efficient way would be in its corresponding helpdesk. A [new issue](https://github.com/ec-jrc/re3gistry/issues/147) has been opened in its repository and this issue will be closed. In case you think this issue is not fully solved, please feel free to open a new issue if you find it necessary. 

Thanks for your help and we encourage you to follow the new issue in case new information is needed.

Regards
