### ISSUE TITLE
Direct uri for language instance

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-registry#30]
Dear Re3Gistry Team,
could you please, help us to identify, how shall looks specific direct URI for SK version of this register?
https://er.hany.sk/inspire_mappings
if we want user to navigate directly to the SK (Slovenčina) instance?
![obrázok](https://user-images.githubusercontent.com/6195936/156265601-01052d7b-4daa-4e37-93da-41c46fc4d338.png)
Thanks, Martin

**Comment by emanuelaepure10** [comment]
Hi Martin,

You should set as master language SK, but you need to be sure that everything in the databse is translated in the Slovakian,
otherwise you might have errors in the interface.

To change the master language go directly in the database and change the column  masterlanguage in the table reg_languagecode. Please restart tomcat after this change. 

You should as well be sure you have here
https://github.com/ec-jrc/re3gistry/tree/master/sources/Re3gistry2/src/main/resources/localizations
or here
https://github.com/ec-jrc/re3gistry/tree/master/dist/app/re3gistry2/WEB-INF/classes/localizations
depending on how you run the app
the localization file LocalizationBundle_sk.properties

For the webapp the sk.json is already present here
https://github.com/ec-jrc/re3gistry/tree/master/dist/webapp/public_html/js-ecl-v2/i18n

Please let us know if you manage to have sk as default

Best regards

**Comment by arantzaetxebarria** [comment]
Dear @MartinTuchyna 

After the analysis, it has been decided that this issue is related to the Re3gistry software and the better place to be solved in the most efficient way would be in its corresponding helpdesk. A [new issue](https://github.com/ec-jrc/re3gistry/issues/146) has been opened in its repository and this issue will be closed. In case you think this issue is not fully solved, please feel free to open a new issue if you find it necessary. 

Thanks for your help and we encourage you to follow the new issue in case new information is needed.

Regards
