### ISSUE TITLE
Country Named Authority List from the Metadata Registry of the Publications Office - External Reference Link not resolvable

### ISSUE THREAD

**Issue by jescriu** [INSPIRE-MIF/helpdesk-registry#34]
The URL stored in the 'External Reference Link' field of the '[Country Named Authority List from the Metadata Registry of the Publications Office](https://inspire.ec.europa.eu/document/CountryCode)' record of the INSPIRE reference document register is not resolvable (not working). 
I am proposing a content change / correction on behalf of Michael Lutz ('EC-JRC' submitting organisation).

- the URI of the register/reference code: https://inspire.ec.europa.eu/document/CountryCode
- the rationale or motivation behind this proposal: The 'External Reference Link' to the document is not properly working.
- the proposed change: Substitute the current value 'http://publications.europa.eu/mdr/authority/country' by the new value 'https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country'.
- the change type: clarification.

NOTE: The Publications Office of the European Union current has a new Internet domain: [https://op.europa.eu/](https://op.europa.eu/). This new domain may have impacted other records/registers of the INSPIRE Registry pointing to the old domain of the Publications Office ([http://publications.europa.eu/](http://publications.europa.eu/)).

**Comment by heidivanparys** [comment]
I'm copying the discussion from [INSPIRE-MIF/helpdesk#151](https://github.com/INSPIRE-MIF/helpdesk/issues/151) in here, see below.

Comment by me:

It seems to me that the descriptions regarding country codes using in the properties below are not consistent.

- AdministrativeBoundary.country
- AdministrativeUnit.country
- MaritimeBoundary.country
- MaritimeZone.country
- VectorStatisticalUnit.country


The country code is defined in the [INSPIRE Generic Conceptual Model](http://inspire.ec.europa.eu/documents/inspire-generic-conceptual-model) and is available in the [Interinstitutional style guide](https://publications.europa.eu/code/en/en-370100.htm).

![billede](https://user-images.githubusercontent.com/11427611/232032854-a4c22403-d579-44e7-82b3-9122749b6e84.png)

In the application schemas (au, su-vector, mu), the `country` properties have `gmd:Country_PropertyType` as type. For example, from https://inspire.ec.europa.eu/schemas/au/4.0/AdministrativeUnits.xsd:

```xml
<element name="country" type="gmd:Country_PropertyType">
<annotation>
<documentation>
-- Name -- country -- Definition -- Two-character country code according to the Interinstitutional style guide published by the Publications Office of the European Union.
</documentation>
</annotation>
</element>
```

In a GML instance document, this gives, e.g. for Denmark:

```xml
   <au:country>
    <gmd:Country codeList="http://inspire.ec.europa.eu/codeList/CountryCode" codeListValue="DK"/>
   </au:country>
```

So because `gmd:Country_PropertyType` is used, the practice of using XLink is not used, so the encoding of country is *not* something like this:

```xml
   <au:country xlink:href="http://inspire.ec.europa.eu/codeList/CountryCode/DK" />
```

although this practice is described in [Guidelines for the encoding of spatial data](http://inspire.ec.europa.eu/documents/guidelines-encoding-spatial-data):

![billede](https://user-images.githubusercontent.com/11427611/232033702-363c86f1-3470-4a5f-ad0f-856f79a6fdf9.png)

When going to https://inspire.ec.europa.eu/codelist/CountryCode, the definition reads “Country code as defined in the Interinstitutional style guide published by the Publications Office of the European Union.”, but the document referred to at https://inspire.ec.europa.eu/document/CountryCode is titled “Country Named Authority List from the Metadata Registry of the Publications Office”, and points to http://publications.europa.eu/mdr/authority/country (which should actually be updated to https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country according to https://github.com/INSPIRE-MIF/helpdesk-registry/issues/34).

However, the “Country Named Authority List from the Metadata Registry of the Publications Office” is another code list. It consists of code values of three letters, as opposed to two in the Interinstitutional style guide.

![billede](https://user-images.githubusercontent.com/11427611/232034655-3340f641-b7a2-4624-a9db-574174176bd0.png)

![billede](https://user-images.githubusercontent.com/11427611/232035418-57f6c47d-1f34-4ccf-a21b-6bba4bd34f71.png)

Using that code list, the data above has to be encoded as follows, using another code, that is DNK instead of DK.

```xml
   <au:country>
    <gmd:Country codeList="http://inspire.ec.europa.eu/codeList/CountryCode" codeListValue="DNK"/>
   </au:country>
```

or as follows:

```xml
   <au:country>
    <gmd:Country codeList="http://publications.europa.eu/resource/authority/country" codeListValue="DNK"/>
   </au:country>
```

Note: The document referred to at http://inspire.ec.europa.eu/codelist/CountryCode was changed at some point, see http://inspire.ec.europa.eu/codelist/CountryCode:1 vs http://inspire.ec.europa.eu/codelist/CountryCode:2.

What code list should be used? The decision may affect the data models and generated schemas (referring textually to the Interinstitutional style guide) and / or the information in the INSPIRE registry regarding CountryCode.

<hr />

Comment by @fabiovinci :

thank you for raising the question, which affects both the registry and the schemas.

Regarding the registry, it seems quite clear that the values that should be used are the two-letter codes since they are listed in the _D2.5 Generic Conceptual Model_ and the definition of the codelist in the UML refers to the "_Interinstitutional style guide published by the Publications Office of the European Union_" which confirms those codes.

![image](https://user-images.githubusercontent.com/22212406/234580426-16fe6e39-a017-4071-a1b9-f3f6369f3bd1.png)

I suggest continuing this discussion in the related issue in the registry helpdesk.

Regarding the schemas, it seems the ISO 19139 data type "gmd:Country_PropertyType" was used instead of "gml:ReferenceType" as for the other attributes that refer to a codelist. If this can be considered wrong, the related change proposal needs to be discussed in the related helpdesk, but the change will break current implementations.

**Comment by heidivanparys** [comment]
Note that the Interinstitutional Style Guide is also mentioned in the IR interoperability, see e.g. the [draft amendment of the IR interoperability](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=pi_com%3AAres%282021%295166256):

![image](https://user-images.githubusercontent.com/11427611/235119341-36192aa8-7360-481a-a3d9-12824361e81c.png)

![image](https://user-images.githubusercontent.com/11427611/235119368-5b307ff8-68e7-4282-89d6-03ef3c39becc.png)

**Comment by arantzaetxebarria** [comment]
As requested in [74th MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/74th+MIG-T+meeting+2023-04-28), in order for the proposal to go ahead, feedback from MIG-T members is needed.

**Comment by arantzaetxebarria** [comment]
In the sub-group meeting on 10/11/2023, the proposal was rejected.
it was decided to create a new proposal to change the link to https://publications.europa.eu/code/en/en-370100.htm (interinstitutional Style Guide) and use the two-letter codes

**Comment by jescriu** [comment]
Dear @heidivanparys,
Would you be able to kindly formulate the new change proposal for using the [Interinstitutional Style Guide](https://publications.europa.eu/code/en/en-370100.htm)?

**Comment by heidivanparys** [comment]
> Dear @heidivanparys, Would you be able to kindly formulate the new change proposal for using the [Interinstitutional Style Guide](https://publications.europa.eu/code/en/en-370100.htm)?

See #71. I would need some input though on how exactly to remove the current inconsistency, see the explanation in that issue.
