### ISSUE TITLE
Updates from backend on frontend

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-registry#35]
Dear Re3gistry team.

Is there some specific action needed in order to see changes executed on backend also on the frontend?

For example I have updated the title of the register "INSPIRE Roz??renia" on this instance: https://er.hany.sk/registry

in backend on "INSPIRE Rozsirenia": see snap, 

![obrázok](https://user-images.githubusercontent.com/6195936/172829241-69d7670b-4f4d-4600-9507-a9fe6075cbc3.png)

but change is not visible on the frontend even in incognito mode after cleared cache..

![obrázok](https://user-images.githubusercontent.com/6195936/172829352-84f7ac3f-5dae-4343-8476-5bb8a41cf189.png)

Thanks,

Martin

**Comment by arantzaetxebarria** [comment]
Dear @MartinTuchyna

As @oscar9 has commented, it has been decided that this issue is related to the Re3gistry software and the better place to be solved in the most efficient way would be in its corresponding helpdesk. A [new issue 155]( https://github.com/ec-jrc/re3gistry/issues/155) has been opened in its repository and this issue will be closed.

Thanks for your help and we encourage you to follow the new issue in case new information is needed.

Regards, Arantza
