### ISSUE TITLE
Change rdf:type of INSPIRE Theme Register concepts from skos:ConceptScheme to skos:Concept

### ISSUE THREAD

**Issue by ODP-hil** [INSPIRE-MIF/helpdesk-registry#44]
In the [INSPIRE Theme Register](url) terms are typed as [skos:ConceptScheme](https://www.w3.org/TR/skos-reference/#schemes). For example:

```<rdf:Description rdf:about="http://inspire.ec.europa.eu/theme/hy">
      <dct:identifier rdf:datatype="http://www.w3.org/2000/01/rdf-schema#Literal">http://inspire.ec.europa.eu/theme/hy</dct:identifier>
      [...]
      <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
      <skos:inScheme rdf:resource="http://inspire.ec.europa.eu/theme"/>
 ```

I believe it would be more accurate to type the single concepts as [skos:Concept](https://www.w3.org/TR/skos-reference/#concepts) while maintaining the rdf:type of the top level <http://inspire.ec.europa.eu/theme> as skos:ConceptScheme.

**Comment by arantzaetxebarria** [comment]
Dear @ODP-hil 

After analysis of this issue, it has been decided that this issue is related to the Re3gistry software, and the best place to be solved in the most efficient way would be in its corresponding helpdesk. A [new issue](https://github.com/ec-jrc/re3gistry/issues/325) has been opened in its repository and this issue will be closed.

Thanks for your help and we encourage you to follow the new issue in case new information is needed.

Regards
