### ISSUE TITLE
Incomplete list of harmonised layers in the registry - Examples for PS Data Theme

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-registry#5]
There are several issues raised regarding the harmonised layer names (and default styles) in the INSPIRE validator, such as https://github.com/INSPIRE-MIF/helpdesk-validator/issues/382 and https://github.com/INSPIRE-MIF/helpdesk-validator/issues/491.

For Protected Sites data theme are missing a lot of harmonised layer names as defined in the TG for PS. As a consequence the INSPIRE validator is triggering fake errors.

![image](https://user-images.githubusercontent.com/20813598/105700167-24b73000-5f11-11eb-821c-ab5f98e21e87.png)

Harmonised layer names that need to be added in the INSPIRE registry for the Protected Sites Data Theme:

Based on https://inspire.ec.europa.eu/codelist/Natura2000DesignationValue:
PS.ProtectedSitesSpecialAreaOfConservation
PS.ProtectedSitesSpecialProtectionArea
PS.ProtectedSitesSiteOfCommunityImportance
PS.ProtectedSitesProposedSpecialProtectionArea
PS.ProtectedSitesProposedSiteOfCommunityImportance

Based on https://inspire.ec.europa.eu/codelist/IUCNDesignationValue:
PS.ProtectedSitesStrictNatureReserve
PS.ProtectedSitesHabitatSpeciesManagementArea
PS.ProtectedSitesManagedResourceProtectedArea
PS.ProtectedSitesNationalPark
PS.ProtectedSitesNaturalMonument
PS.ProtectedSitesProtectedLandscapeOrSeascape
PS.ProtectedSitesWildernessArea

Based on https://inspire.ec.europa.eu/codelist/DesignationSchemeValue:
PS.ProtectedSitesIUCN
PS.ProtectedSitesNatura2000
PS.ProtectedSitesRamsar
PS.ProtectedSitesNationalMonumentsRecord
PS.ProtectedSitesUNESCOManAndBiosphereProgramme
PS.ProtectedSitesUNESCOWorldHeritage
PS.ProtectedSitesEmeraldNetwork

Based on https://inspire.ec.europa.eu/enumeration/ProtectionClassificationValue:
PS.ProtectedSitesNatureConservation
PS.ProtectedSitesArcheaological
PS.ProtectedSitesCultural
PS.ProtectedSitesEcological
PS.ProtectedSitesLandscape
PS.ProtectedSitesEnvironment
PS.ProtectedSitesGeological

Note:
https://inspire.ec.europa.eu/codelist/IUCNDesignationValue/ProtectedLandscapeOrSeascape is incorrect, as the first character should not be a capital leter, so the correct registry value should be
https://inspire.ec.europa.eu/codelist/IUCNDesignationValue/protectedLandscapeOrSeascape
Protected -> protected.

**Comment by hernlor** [comment]
Dear @iuriemaxim , thank you for your request.

First of all, apologies on behalf of the INSPIRE Registry team for the delay in reacting. 

We are in transition from the former issue tracker and we were setting up the governance workflow (not completely finished yet).

Indeed,  there are layers appearing in the technical guidelines that do not appear in the registry. The reason is explained in the content summary of the code list register "_The INSPIRE code list register contains the code lists and their values, as defined in the INSPIRE implementing rules on interoperability of spatial data sets and services (Commission Regulation (EU) No 1089/2010). 
NOTE: It does not yet include references to external code lists and the additional code lists and extended values proposed in the Data Specification Technical Guidelines._"

We are in touch with the INSPIRE Validator colleagues to overcome these issues. However, if you deem that change to be a priority, please get in touch with your respective submitting organisation. 

Please remember that requests impacting the content of the INSPIRE registry are reserved exclusively to the appointed submitting organisations. Contact details of the appointed submitting organisations are available here: https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/submitting-organisations-list.md

Kind regards, 
INSPIRE Registry team

**Comment by iuriemaxim** [comment]
@hernlor Thank you for reply, However, even if you decided to close the incident, please look in the Commission Regulation (EU) No 1089/2010) in order to see that all the layer names that I mentioned that are missing from the INSPIRE Registry, are actually listed in the Commission Regulation (EU) No 1089/2010)  as can be seen also in the image below starting with section 9.4

![image](https://user-images.githubusercontent.com/20813598/112504900-e9ac6e00-8d94-11eb-86cc-76b185cf13e2.png)

However the only harmonised layer name that is listed in the Registry at https://inspire.ec.europa.eu/layer is PS.ProtectedSites

![image](https://user-images.githubusercontent.com/20813598/112505891-e4035800-8d95-11eb-86f5-3dd5275bbe35.png)

So the incident was to indicate that the legal harmonised names are missing from the registry, not to ask for addition of suplementary ones.

@hernlor Please then first reopen the incident and reconsider if necessary to change the answer.
