### ISSUE TITLE
missing CORS header 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by celinevil** [INSPIRE-MIF/helpdesk-registry#55]
When creating a thesaurus from the INSPIRE registry in Geonetwork, the registry item class remains empty. Thereby, it isn't possible to upload a new thesaurus. 
The problem seems to be related to a missing CORS header 'Access-Control-Allow-Origin' in the response for the type of url "https://inspire.ec.europa.eu/registry/registry.xx.json". Is it possible to add this header to the response ?
Thank you in advance.

**Comment by arantzaetxebarria** [comment]
Dear @celinevil 

Thanks for reporting the issue, we will analyze your proposal to add the header to the response. We will keep you informed of the conclusions we reach.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @celinevil 

After a first analysis of this issue, it has been decided that this issue is related to the Re3gistry software, and the best place to be solved in the most efficient way would be in its corresponding helpdesk. A [new issue](https://github.com/ec-jrc/re3gistry/issues/326) has been opened in its repository and this issue will be closed.

Thanks for your help and we encourage you to follow the new issue in case new information is needed.

Regards
