### ISSUE TITLE
Reusable JSON-LD context(s)

### ISSUE THREAD

**Issue by saxomoose** [INSPIRE-MIF/helpdesk-registry#64]
I am looking for reusable JSON-LD context(s) of the INSPIRE vocabularies. I see that the INSPIRE registry does expose some data in RDF/XML. Maybe someone somewhere made the effort of creating JSON-LD context(s)?

**Comment by saxomoose** [comment]
I found this workspace / org: https://github.com/inspire-eu-rdf.
It is technically possible to draw the necessary linked data artefacts from these ontologies (JSON-LD contexts,...).
However, the last commit on [inspire-rdf-vocabularies](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies) dates back to 6 years ago. Is there any plan to revive this initiative?

**Comment by arantzaetxebarria** [comment]
Dear @saxomoose 

Thanks for reporting the issue, we will work on analyzing your approach. We will come back to you.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @saxomoose 

After analysis of this issue, it has been decided that this issue is related to the Re3gistry software, and the best place to be solved in the most efficient way would be in its corresponding helpdesk. A [new issue](https://github.com/ec-jrc/re3gistry/issues/327) has been opened in its repository and this issue will be closed.

Thanks for your help and we encourage you to follow the new issue in case new information is needed.

Regards
