### ISSUE TITLE
The code list for the country codes has to refer to the Interinstitutional style guide

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/helpdesk-registry#71]
The code list for the country codes, https://inspire.ec.europa.eu/codelist/CountryCode, has to refer to the Interinstitutional style guide, available at https://publications.europa.eu/code/en/en-000100.htm. This is required by the [regulation on the interoperability of spatial data sets and services](https://eur-lex.europa.eu/eli/reg/2023/2431/oj#d1e198-4-1).

Currently, the [code list for the country codes](https://inspire.ec.europa.eu/codelist/CountryCode) refers to the Country Named Authority List from the Metadata Registry of the Publications Office, which is available at https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country.

This issue results from the discussion in #34.

**Comment by heidivanparys** [comment]
It is currently not clear to me what the best way would be to actually do this change.

The document referred to at http://inspire.ec.europa.eu/codelist/CountryCode was changed at some point, see http://inspire.ec.europa.eu/codelist/CountryCode:1 vs http://inspire.ec.europa.eu/codelist/CountryCode:2.

The current version refers to https://inspire.ec.europa.eu/document/CountryCode, the _Country Named Authority List from the Metadata Registry of the Publications Office_, the old version referred to https://inspire.ec.europa.eu/document/CountrieCode, _EU-28 and candidate countries'. Countries, languages and currencies: names, codes and listing order_. The external reference link for the latter does not work any more. Was that an old link to the Interinstitutional style guide?

Should https://inspire.ec.europa.eu/document/CountryCode be updated? Or should https://inspire.ec.europa.eu/document/CountrieCode be updated, and at the same time http://inspire.ec.europa.eu/codelist/CountryCode be updated to point to https://inspire.ec.europa.eu/document/CountrieCode instead?

**Comment by jescriu** [comment]
Dear colleagues,

The current issue - #71, and the related issue #34, seem to be derived from a series of unfortunate changes that were done to the INSPIRE Registry in the past.

After analysing them for a long time today, I came up with a proposal to be discussed next Monday in the Action 2.3.1 INSPIRE-artefacts Sub-group meeting.

I started analysing the related items from the INSPIRE reference document register.

<h4>Considerations</h4>

A. **https://inspire.ec.europa.eu/document/CountrieCode** item - It currently has an *Invalid* status in the registry. It was inserted in the INSPIRE Registry on 18-08-2015 and invalidated just 6 days after, on 24-08-2015. 
The reason for the invalidation was probably the wrong spelling of its URI (Countr**ie**Code), since the URI acts as unique identifier of registry items. 

This item was replaced by https://inspire.ec.europa.eu/document/CountryCode (See B below).

Its 'Label' attribute is populated as '_EU-28 and candidate countries'. Countries, languages and currencies: names, codes and listing order.'_ - indicating that the item was intended to refer the two-letter country codes from the [Interinstitutional Style Guide](https://publications.europa.eu/code/en/en-370100.htm) - which nowadays is composed by 27 countries (28 countries minus the UK, which left the European Union):

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/22743378/6d04d940-9bb2-4856-965c-8a1f8d5ab707)

And as @heidivanparys stated [here](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/71#issuecomment-1814782211), its 'External reference link' does not work any more (pointing to an old EUROSTAT domain).

B.  **https://inspire.ec.europa.eu/document/CountryCode** item - It was inserted on 24-08-2025 as successor of the previous item, and has a *Valid* status.
However, **its External reference link** (with value 'http://publications.europa.eu/mdr/authority/country') is outdated and **SHALL be changed**.

C. There was a 1:1 relationship between **https://inspire.ec.europa.eu/codelist/CountryCode:1** and **https://inspire.ec.europa.eu/document/CountrieCode**, as it can be deduced from the descriptor of its 'Document' attribute ('_EU-28 and candidate countries'. Countries, languages and currencies: names, codes and listing order._'). 
Note: the URL of the 'Document' attribute is useless, since it is self-referencing the own item (pointing to 'http://inspire.ec.europa.eu/codelist/CountryCode').

<h4>Consequently / PROPOSAL</h4>

1 -  The **CountryCode code list** (http://inspire.ec.europa.eu/codelist/CountryCode) **WAS originally intended to refer to the two-letter country codes** advised in the [Interinstitutional Style Guide](https://publications.europa.eu/code/en/en-370100.htm) - as stated in its 'Definition' attribute ('_Country code as defined in the Interinstitutional style guide published by the Publications Office of the European Union._').

As stated in the Guide, this is equivalent to: 

- For Member States - using '_the two-letter ISO code should be used ([ISO 3166 alpha-2](https://www.iso.org/obp/ui/#search/code/)), except for Greece, for which the abbreviation EL is recommended_'. 
- For non-EU countries - advisably - using '_the two-character ISO code [(ISO 3166 alpha-2).](https://www.iso.org/obp/ui/#search/code/)_'.

2 - Given C above, and since 'https://inspire.ec.europa.eu/document/CountrieCode' is currently Invalid, then **https://inspire.ec.europa.eu/codelist/CountryCode:1** (currently having a _Valid_ status) **SHALL be Invalidated** correspondingly.

3 - **https://inspire.ec.europa.eu/codelist/CountryCode:2** (currently having a _Valid_ status) **SHALL continue referring the two-letter country codes** - as also stated in its 'Definition' attribute ('_Country code as defined in the Interinstitutional style guide published by the Publications Office of the European Union._'), equally to its previous version.
Otherwise it would be inconsistent to the original purpose of this code list.

Therefore, **its 'Document' attribute MUST be modified**:

- from URL: 'http://inspire.ec.europa.eu/document/CountryCode' (with the '_Country Named Authority List from the Metadata Registry of the Publications Office_' descriptor).
- **to** URL: 'https://publications.europa.eu/code/en/en-370100.htm#fn2' (with the '_Interinstitutional style guide published by the Publications Office of the European Union._' descriptor).

4 - Before applying the proposed changes, **VALIDATE this approach with the [Publications Office of the European Union](https://op.europa.eu/en/home)**, especially in terms of validity of country code lists proposed and their reference links.

<h4>Additionally</h4>

5 - In case any need for referring countries using the three-letter codes is identified (e.g. from 'https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country'), then a new separated item could be possibly added in the future in the INSPIRE Reference document register.

**Comment by arantzaetxebarria** [comment]
The INSPIRE MIG-T approved the change proposal during the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17)

**Comment by arantzaetxebarria** [comment]
We want to inform you that the proposal has been successfully published.

https://inspire.ec.europa.eu/codelist/CountryCode

Regards
