### ISSUE TITLE
rdf format of inspire registratie not available

### ISSUE THREAD

**Issue by onderwijsarchitectuur** [INSPIRE-MIF/helpdesk-registry#74]
- go to https://inspire.ec.europa.eu/codelist/BuildingNatureValue/arch
- click on button rdf/xml
- message: cannot be downloaded safely

Button xml and json do work

Thanks

**Comment by arantzaetxebarria** [comment]
Dear @onderwijsarchitectuur 

Regarding the issue you're experiencing with downloading the RDF distribution of the INSPIRE theme register, it seems that the URL for the download link begins with "http://", which may cause certain browsers like Chrome to block the download due to security reasons.

To address this, we recommend trying to download the RDF distribution using a browser like Microsoft Edge. Edge may display a message prompting you to accept the download despite the insecure connection.

If you have any other questions or need further assistance, don't hesitate to ask us.

Regards
