### ISSUE TITLE
INSPIRE theme register RDF distribution

### ISSUE THREAD

**Issue by jescriu** [INSPIRE-MIF/helpdesk-registry#95]
Adding here an issue which arrived to the JRC INSPIRE Support functional mail box.
I am redirecting the user to this GitHub thread.
_____________________________________________________________________________________

Dear Inspire team,

I am contacting you from the EU Vocabularies team of Publications Office.

We have received a request to explore the possibility to align [INSPIRE theme register - INSPIRE registry (europa.eu)](https://inspire.ec.europa.eu/theme) with our [High-value dataset categories - EU Vocabularies - Publications Office of the EU (europa.eu)](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/high-value-dataset-category)
Due to the nature of our alignment process, in doing so it is necessary to interact with an RDF distribution of the Inspire theme register.
It looks like the online catalogue does not allow me to download such a distribution. 
Can you please guide me on what I need to do to get a current version of this distribution?

Tried first to use email address provided as the: Contact Point [JRC INSPIRE Registry Team](mailto:inspire-registry-dev@jrc.ec.europa.eu)
but it looks like the respective address it is not functional any more.

Kind regards,
Mihai

Mihai PAUNESCU 

A.1.002 - Reference Data and Style Guide
Publications Office of the European Union 
Directorate A – Data, Information and Knowledge Management Services
A.1 – Data and Format Standardisation Services
20, rue de Reims • L-2417 Luxembourg
_____________________________________________________________________________________

**Comment by iratigarzon** [comment]
Dear Mihai,

Regarding the issue you're experiencing with downloading the RDF distribution of the INSPIRE theme register, it seems that the URL for the download link begins with "http://", which may cause certain browsers like Chrome to block the download due to security reasons.

To address this, we recommend trying to download the RDF distribution using a browser like Microsoft Edge. Edge may display a message prompting you to accept the download despite the insecure connection.

If you have any other questions or need further assistance, don't hesitate to ask us.

Regards,
Irati.

**Comment by arantzaetxebarria** [comment]
Dear Mihai

This issue is closed as it has been answered, if you have any other questions, please do not hesitate to contact us. 

Regards,

Arantza
